frontend/AMS.frontend/AMS.frontend.web/Areas/Operations/Models/Cycle/CycleModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AMS.frontend.web.Areas.Operations.Models.Cycle
{
    public class CycleModel
    {
        [NotMapped]
        public string Id { get; set; }

        [JsonIgnore]
        public int NumericId => Convert.ToInt32(Id);

        public string Name { get; set; }

        [Required]
        public DateTime? StartDate { get; set; }

        [Required]
        public DateTime? EndDate { get; set; }

        [Required]
        [Display(Name ="Previous Cycle")]
        public string PreviousCycle { get; set; }

        [JsonIgnore]
        public int NumericPreviousCycle =>
            string.IsNullOrWhiteSpace(PreviousCycle) ? 0 : Convert.ToInt32(PreviousCycle);

        [JsonIgnore]
        public string StartDateForDisplay => StartDate?.ToString("dd/MM/yyyy");


        [JsonIgnore]
        public string EndDateForDisplay => EndDate?.ToString("dd/MM/yyyy");

        [JsonIgnore]
        public string CycleNameForDisplay => StartDate?.ToString("yyyy") +"-"+ EndDate?.ToString("yyyy");
    }
}

frontend/AMS.frontend/AMS.frontend.web/Areas/Operations/Models/Cycle/MidTermCycle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AMS.frontend.web.Areas.Operations.Models.Cycle
{
    public class MidTermCycle
    {
        [Required]
        public string Institution { get; set; }

        [Required]
        public string Position { get; set; }

        [Required]

        public DateTime? StartDate { get; set; }

        [Required]
        public DateTime? EndDate { get; set; }

        [NotMapped]
        public string CycleId { get; set; }
    }
}

frontend/AMS.frontend/AMS.frontend.web/Areas/Operations/Controllers/CycleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AMS.frontend.web.Areas.Operations.Models;
using AMS.frontend.web.Areas.Operations.Models.Cycle;
using AMS.frontend.web.Extensions;
using AMS.frontend.web.Helpers.Constants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AMS.frontend.web.Areas.Operations.Controllers
{
    [Area(AreaNames.Operations)]
    public class CycleController : BaseController
    {

        private readonly ILogger<CycleController> _logger;

        public CycleController(ILogger<CycleController> logger)
        {
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            var allCycles = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).GetAllCycles();
            return View(allCycles);
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.PreviousCycle = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).GetCycles();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CycleModel model)
        {
            bool success = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).CreateNewCycle(model);

            if (success)
            {
                TempData["MessageType"] = MessageTypes.Success;
                TempData["Message"] = Messages.CycleCreated;

                ViewBag.MessageType = MessageTypes.Success;
                ViewBag.Message = Messages.CycleCreated;

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.PreviousCycle = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).GetCycles();

                ViewBag.MessageType = MessageTypes.Error;
                ViewBag.Message = Messages.GeneralError;
            }

            return View();
        }

        public async Task<IActionResult> Appoint(MidTermCycle model)
        {
            var success = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).appoint(model.CycleId);

            if (success)
            {
                TempData["MessageType"] = MessageTypes.Success;
                TempData["Message"] = Messages.CycleAppoint;

                ViewBag.MessageType = MessageTypes.Success;
                ViewBag.Message = Messages.CycleAppoint;
            }
            else
            {
                ViewBag.MessageType = MessageTypes.Error;
                ViewBag.Message = Messages.GeneralError;
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Close(MidTermCycle model)
        {
            var success = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).close(model);

            if (success)
            {
                TempData["MessageType"] = MessageTypes.Success;
                TempData["Message"] = Messages.CycleClosed;

                ViewBag.MessageType = MessageTypes.Success;
                ViewBag.Message = Messages.CycleClosed;
            }
            else
            {
                ViewBag.MessageType = MessageTypes.Error;
                ViewBag.Message = Messages.GeneralError;
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(string id)
        {
            ViewBag.Institution = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).GetPositionInstitution();

            return View(new MidTermCycle {CycleId = id });
        }

        public async Task<JsonResult> GetAllPositionOfInstitution(string uid)
        {
            var list = await new RestfulClient(_logger,HttpContext.Session.Get<AuthenticationResponse>("AuthenticationResponse")?.Token).findPositionByInstituionId(uid);

            return new JsonResult(list);
        }
    }
}

frontend/AMS.frontend/AMS.frontend.web/Areas/Operations/Views/Cycle/Create.cshtml
@model AMS.frontend.web.Areas.Operations.Models.Cycle.CycleModel
@{
    ViewBag.ModuleTitle = "Create Cycle";
    ViewBag.PageTitle = "Create Cycle";
}

<div class="row">
    <div class="col-lg-12">
        <!--begin::Portlet-->
        <div class="m-portlet">
            <!--begin::Form-->
            <form id="mainForm" asp-area="@AreaNames.Operations" asp-controller="@ControllerNames.Cycle" asp-action="Create" method="post" class="m-form m-form--fit m-form--label-align-right" enctype="multipart/form-data">
                <div class="m-portlet__body">
                    <div class="form-group m-form__group row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label><span class="required">*</span>
                                <div class="input-group">
                                    <input type="text" asp-for="StartDate" class="form-control date-picker" placeholder="Select date">
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="basic-addon2">
                                            <i class="la la-calendar"></i>
                                        </span>
                                    </div>
                                </div>
                                <span asp-validation-for="StartDate" class="form-control-feedback"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label><span class="required">*</span>
                                <div class="input-group">
                                    <input type="text" asp-for="EndDate" class="form-control date-picker" placeholder="Select date">
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="basic-addon2">
                                            <i class="la la-calendar"></i>
                                        </span>
                                    </div>
                                </div>
                                <span asp-validation-for="EndDate" class="form-control-feedback"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="PreviousCycle" class="control-label"></label>
                                <select asp-for="PreviousCycle" asp-items="@ViewBag.PreviousCycle" class="form-control m-select2" placeholder="Select Previous Cycle">
                                    <option></option>
                                </select>
                                <span asp-validation-for="PreviousCycle" class="form-control-feedback"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                    <div class="m-form__actions m-form__actions--solid m--align-right">
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-save"></i> Add
                        </button>
                        <a asp-area="@AreaNames.Operations" asp-controller="@ControllerNames.Cycle" asp-action="@ActionNames.Index" class="btn default">
                            <i class="fa fa-close"></i> Cancel
                        </a>
                    </div>
                </div>
            </form>
            <!--end::Form-->
        </div>
        <!--end::Portlet-->
    </div>
</div>

frontend/AMS.frontend/AMS.frontend.web/Areas/Operations/Views/Cycle/Detail.cshtml
@model AMS.frontend.web.Areas.Operations.Models.Cycle.MidTermCycle
@{
    ViewBag.ModuleTitle = "Cycle info ";
    ViewBag.PageTitle = "Cycle info";
}

<div class="m-portlet m-portlet--tabs">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    Cycle Info
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs-line m-tabs-line--primary m-tabs-line--2x" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active show" data-toggle="tab" href="#m_tabs_6_1" role="tab" aria-selected="true">
                        Appoint
                    </a>
                </li>
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_tabs_6_2" role="tab" aria-selected="false">
                        Mid Term
                    </a>
                </li>
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_tabs_6_3" role="tab" aria-selected="false">
                        Close Cycle
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="tab-content">
            <div class="tab-pane active show" id="m_tabs_6_1" role="tabpanel">
                <form id="mainForm" asp-area="@AreaNames.Operations" asp-controller="@ControllerNames.Cycle" asp-action="Appoint" method="post" class="m-form m-form--fit m-form--label-align-right" enctype="multipart/form-data">
                    <input type="hidden" asp-for="CycleId">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-save"></i> Appoint
                    </button>
                </form>
            </div>
            <div class="tab-pane" id="m_tabs_6_2" role="tabpanel">
                <form id="mainForm" asp-area="@AreaNames.Operations" asp-controller="@ControllerNames.Cycle" asp-action="" method="post" class="m-form m-form--fit m-form--label-align-right" enctype="multipart/form-data">
                    <div class="form-group m-form__group row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="Institution" class="control-label"></label>
                                <select asp-for="Institution" asp-items="@ViewBag.Institution" class="form-control institution-select" placeholder="Select">
                                    <option></option>
                                </select>
                                <span asp-validation-for="Institution" class="form-control-feedback"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="Position" class="control-label"></label>
                                <select asp-for="Position" asp-items="@ViewBag.Position" class="form-control position-select" placeholder="Select">
                                    <option></option>
                                </select>
                                <span asp-validation-for="Position" class="form-control-feedback"></span>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <div class="input-group">
                                    <input type="text" asp-for="StartDate" class="form-control date-picker" placeholder="Select date">
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="basic-addon2">
                                            <i class="la la-calendar"></i>
                                        </span>
                                    </div>
                                </div>
                                <span asp-validation-for="StartDate" class="form-control-feedback"></span>
                            </div>
                        </div>
                        <div class="m-form__actions" style="padding-left: 15px !important; padding-top: 28px !important">
                            <button type="button" class="btn btn-warning">
                                <i class="fa fa-save"></i> Add
                            </button>
                        </div>
                    </div>
                    <div class="form-group m-form__group row">
                        <div class="col-lg-12" id="midTermCycle-table">
                            @{
                                await Html.RenderPartialAsync("_MidTermCycleTablePartial", Model).ConfigureAwait(false);
                            }
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                        <div class="m-form__actions m--align-right">
                            <button id="SaveMidTerm" type="submit" class="btn btn-success">
                                <i class="fa fa-save"></i> Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane" id="m_tabs_6_3" role="tabpanel">
                <form id="mainForm" asp-area="@AreaNames.Operations" asp-controller="@ControllerNames.Cycle" asp-action="Close" method="post" class="m-form m-form--fit m-form--label-align-right" enctype="multipart/form-data">
                    <div class="col-lg-3">
                        <input type="hidden" asp-for="CycleId">
                        <div class="form-group">
                            <label asp-for="EndDate" class="control-label"></label>
                            <div class="input-group">
                                <input type="text" asp-for="EndDate" class="form-control date-picker" placeholder="Select date">
                                <div class="input-group-append">
                                    <span class="input-group-text" id="basic-addon2">
                                        <i class="la la-calendar"></i>
                                    </span>
                                </div>
                            </div>
                            <span asp-validation-for="EndDate" class="form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <button type="submit" class="btn btn-success">
                            <i class="la la-close"></i> Close Cycle
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/extensions/buttons.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/extensions/colreorder.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/extensions/responsive.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/data-sources/ajax-server-side.js" type="text/javascript"></script>

    <script type="text/javascript">
        jQuery(document).ready(function () {

            var x = document.getElementById("subHeader");
            x.style.display = "none";

            MakeCascadingDropDown("institution-select",
            "position-select",
            "@Url.Action(ActionNames.GetAllPositionOfInstitution, ControllerNames.Cycle, new {area = AreaNames.Operations})");

        });
    </script>
}

frontend/AMS.frontend/AMS.frontend.web/Areas/Operations/Views/Cycle/Index.cshtml
@model IEnumerable<AMS.frontend.web.Areas.Operations.Models.Cycle.CycleModel>
@{
    ViewBag.ModuleTitle = "All Cycles";
    ViewBag.PageTitle = "All Cycles";
}

@section styles{
    <link href="~/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
}
<div class="m-portlet m-portlet--mobile" id="person-list-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-list-1"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Cycle Listing
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="#" data-portlet-tool="toggle" class="m-portlet__nav-link m-portlet__nav-link--icon">
                        <i class="la la-angle-down"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="m-form m-form--label-align-left m--margin-bottom-20">
            <div class="row align-items-center">
                <div class="col-xl-12 order-1 order-xl-2 m--align-left">
                    <a asp-controller="Cycle" asp-action="Create" class="btn btn-primary">
                        <span>
                            <i class="la la-user-plus"></i>
                            <span>
                                Add New Cycle
                            </span>
                        </span>
                    </a>
                    <div class="m-separator m-separator--dashed d-xl-none"></div>
                </div>
            </div>
        </div>
        <table id="cycles" class="table table-striped- table-bordered table-hover">
            <thead>
                <tr>
                    <th> Cycle </th>
                    <th> Start Date </th>
                    <th> End Date </th>
                    <th> Actions </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.StartDateForDisplay</td>
                        <td>@item.EndDateForDisplay</td>
                        <td>
                            <button type="button" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only" title="View"  onclick="@("window.location.href='" + @Url.Action("Detail", "Cycle", new { id = item.Id }) + "'");">
                                <i class="la la-eye"></i>
                            </button>
                            <button type="button" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only" title="Edit">
                                <i class="la la-edit"></i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section scripts{
    <script src="~/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/extensions/buttons.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/extensions/colreorder.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/extensions/responsive.js" type="text/javascript"></script>
    <script src="~/assets/demo/default/custom/crud/datatables/data-sources/ajax-server-side.js" type="text/javascript"></script>

    <script type="text/javascript">
        jQuery(document).ready(function () {

            var x = document.getElementById("subHeader");
            x.style.display = "none";

        });
    </script>
}